[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# Copied from https://github.com/bbstilson/adventofcode

[dependencies]
anyhow = "1.0.65"
bitvec = "1.0.1"
fancy-regex = "0.13.0"
home = "0.5.4"
itertools = "0.13.0"
lazy_static = "1.4.0"
num = "0.4.1"
once_cell = "1.18.0"
rand = "0.8.5"
regex = "1.7.0"
reqwest = { version = "0.12", features = ["blocking", "json", "cookies"] }
md-5 = "0.10.6"
hex = "0.4"
petgraph = "0.6.5"
serde = "1.0.204"
serde_json = "1.0.121"
